(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const FALLBACK='https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1000&q=80';
let news=[],cat='all',sort='smart',lastUpdated='';
const cats=[['all','सबै'],['nepal','नेपाल'],['politics','राजनीति'],['finance','अर्थतन्त्र'],['sports','खेलकुद'],['tech','प्रविधि'],['entertainment','मनोरञ्जन'],['world','विश्व']];
const image=x=>x.thumb||x.image||FALLBACK;
const age=d=>{const m=Math.floor((Date.now()-new Date(d))/60000);return !Number.isFinite(m)||m<0?'अहिले':m<60?m+' मिनेट अघि':m<1440?Math.floor(m/60)+' घण्टा अघि':Math.floor(m/1440)+' दिन अघि'};
const freshness=d=>{const m=Math.max(0,(Date.now()-new Date(d))/3600000);return Math.max(0,100-m*7)};
function score(x){return (Number(x.isBreaking)?40:0)+(Number(x.sourceCount||1)*12)+freshness(x.pubDate)+(x.desc?.length>120?4:0)}
function filtered(){const q=$('#q').value.trim().toLocaleLowerCase('ne-NP');let d=news.filter(x=>(cat==='all'||x.category===cat||x.storyCategory===cat)&&(!q||[x.title,x.desc,x.source,x.storyId].join(' ').toLocaleLowerCase('ne-NP').includes(q)));if(sort==='latest')d.sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate));else if(sort==='coverage')d.sort((a,b)=>Number(b.sourceCount||0)-Number(a.sourceCount||0));else d.sort((a,b)=>score(b)-score(a));return d}
function setPills(){const el=$('#categories');el.innerHTML=cats.map(([v,t])=>`<button class="${v===cat?'active':''}" data-cat="${v}">${t}</button>`).join('');el.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;setPills();render()});const f=$('#filters');f.innerHTML=[['smart','⚡ स्मार्ट'],['latest','🕒 नयाँ'],['coverage','📡 धेरै स्रोत']].map(([v,t])=>`<button class="${v===sort?'active':''}" data-sort="${v}">${t}</button>`).join('')+cats.filter(x=>x[0]!=='all').map(([v,t])=>`<button data-cat="${v}" class="${v===cat?'active':''}">${t}</button>`).join('');f.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{sort=b.dataset.sort;setPills();render()});f.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;setPills();render()})}
function sourceStats(){const m=new Map();news.forEach(x=>m.set(x.source,(m.get(x.source)||0)+1));return [...m].sort((a,b)=>b[1]-a[1])}
function render(){const data=filtered();const sources=sourceStats();const meta=`${data.length} खबर · ${sources.length} स्रोत · ${lastUpdated?'अपडेट '+age(lastUpdated):'लाइभ इन्जिन'}`;$('#status').textContent=meta;const h=data[0]||news[0];if(h)$('#hero').innerHTML=`<img src="${esc(image(h))}" alt="${esc(h.title)}" loading="eager"><div class="hero-content"><small>${h.isBreaking?'🔴 ब्रेकिङ':'⚡ स्मार्ट छनोट'} · ${esc(h.source||'नेपाल')} · ${age(h.pubDate)}</small><h1>${esc(h.title)}</h1><p>${esc(h.desc||'नेपालका ताजा समाचार र महत्वपूर्ण अपडेटहरू।')}</p></div>`;
const breaking=news.find(x=>x.isBreaking)||news[0];$('#breaking span').textContent=breaking?.title||'ताजा समाचार उपलब्ध छैन';
$('#stories').innerHTML=data.slice(0,18).map((x,i)=>`<button class="story" data-reel="${i}"><div class="story-ring"><img src="${esc(image(x))}" alt="" loading="lazy"></div><b>${esc(x.source||'समाचार')}</b></button>`).join('');
const ranked=[...news].sort((a,b)=>score(b)-score(a));$('#topics').innerHTML=ranked.slice(0,6).map(x=>`<div class="topic glass"><strong># ${esc((x.title||'समाचार').split(/\s+/).slice(0,5).join(' '))}</strong><small>${x.sourceCount||1} स्रोत · ${age(x.pubDate)}</small></div>`).join('');
const people=extractPeople(news).slice(0,8);$('#people').innerHTML=people.map(p=>`<div class="person glass"><strong>👤 ${esc(p.name)}</strong><small>${p.count} समाचारमा उल्लेख</small></div>`).join('')||'<div class="person glass"><strong>👤 व्यक्ति डेटा तयार हुँदैछ</strong></div>';
$('#feed').innerHTML=data.length?data.slice(0,120).map(x=>`<article class="card glass"><div class="card-img"><img src="${esc(image(x))}" alt="${esc(x.title)}" loading="lazy"></div><div class="card-body"><div class="meta">${esc(x.source||'समाचार')} ${x.sourceCount>1?`· ${x.sourceCount} स्रोत`:''}</div><div class="time">${age(x.pubDate)} · ${esc(x.category||'नेपाल')}</div><h3>${esc(x.title)}</h3><p>${esc(x.desc||'')}</p><a class="read" href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">पूरा समाचार ↗</a></div></article>`).join(''):'<div class="empty glass">समाचार भेटिएन।</div>';
$('#stories').querySelectorAll('[data-reel]').forEach(b=>b.onclick=()=>openReels(Number(b.dataset.reel)));}
function extractPeople(items){const counts=new Map(),stop=new Set(['नेपाल','सरकार','राष्ट्रपति','प्रधानमन्त्री','मन्त्री','काठमाडौं','आज','भने','गरे','गर्न','सहित','विरुद्ध','बारे','पछि','अघि','संसद','प्रदेश','जिल्ला','प्रहरी']);items.slice(0,500).forEach(x=>{const words=String(x.title||'').match(/[\u0900-\u097F]{2,}(?:\s+[\u0900-\u097F]{2,})?/g)||[];words.forEach(w=>{w=w.trim();if(!stop.has(w)&&w.split(/\s+/).length<=3)counts.set(w,(counts.get(w)||0)+1)})});return [...counts].map(([name,count])=>({name,count})).filter(x=>x.count>1).sort((a,b)=>b.count-a.count)}
function openReels(start=0){const d=$('#reelDialog'),r=$('#reelFeed');r.innerHTML=filtered().slice(0,120).map(x=>`<article class="reel"><img src="${esc(image(x))}" alt="${esc(x.title)}"><div class="reel-content"><small>${x.isBreaking?'🔴 ब्रेकिङ':'⚡ स्मार्ट'} · ${esc(x.source||'नेपाल')} · ${age(x.pubDate)}</small><h2>${esc(x.title)}</h2><p>${esc(x.desc||'')}</p><a class="read" href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">पूरा समाचार ↗</a></div></article>`).join('');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');requestAnimationFrame(()=>r.scrollTo({top:start*innerHeight,behavior:'instant'}))}
async function load(){try{const cached=localStorage.getItem('nnh-v3-cache');if(cached){const c=JSON.parse(cached);if(c?.items){news=c.items;lastUpdated=c.updatedAt||''}}render();const res=await fetch('./news.json?ts='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error('news fetch failed');const data=await res.json();news=Array.isArray(data.items)?data.items:[];lastUpdated=data.updatedAt||new Date().toISOString();localStorage.setItem('nnh-v3-cache',JSON.stringify({updatedAt:lastUpdated,items:news.slice(0,1000)}));setPills();render()}catch(e){render();$('#status').textContent=news.length?`${news.length} क्यास खबर · स्रोत इन्जिन अफलाइन`:'समाचार फिड उपलब्ध छैन'}}
$('#q').addEventListener('input',render);$('#refresh').onclick=load;$('#reelsBtn').onclick=()=>openReels(0);$('#bottomReels').onclick=()=>openReels(0);$('#closeReels').onclick=()=>$('#reelDialog').close();document.querySelectorAll('.bottom button[data-go]').forEach(b=>b.onclick=()=>$(b.dataset.go==='top'?'.topbar':'#'+b.dataset.go)?.scrollIntoView({behavior:'smooth'}));setPills();load();setInterval(load,180000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
