import json,re
from pathlib import Path
from html import escape
ROOT=Path('.');data=json.loads((ROOT/'news.json').read_text(encoding='utf-8'));items=data.get('items',[]);OUT=ROOT/'news-pages';OUT.mkdir(exist_ok=True)
def slug(s):return (re.sub(r'[^\w\u0900-\u097f]+','-',str(s).lower()).strip('-')[:100] or 'news')
used={}
def name_for(item,i):
 base=slug(item.get('title','news')); n=used.get(base,0);used[base]=n+1;return base if n==0 else f'{base}-{n+1}'
def page(item,url,related):
 t=escape(item.get('title','नेपाल समाचार'));d=escape((item.get('desc') or t)[:220]);img=escape(item.get('thumb',''));pub=escape(item.get('pubDate',''));src=escape(item.get('source','समाचार स्रोत'));cat=escape(item.get('storyCategory',item.get('category','नेपाल')));links=''.join(f'<li><a href="{escape(r)}.html">सम्बन्धित रिपोर्ट</a></li>' for r in related)
 return f'''<!doctype html><html lang="ne"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>{t} | नेपाल न्यूज हब</title><meta name="description" content="{d}"><link rel="canonical" href="{url}"><meta property="og:type" content="article"><meta property="og:title" content="{t}"><meta property="og:description" content="{d}"><meta property="og:image" content="{img}"><meta property="article:published_time" content="{pub}"><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@type':'NewsArticle','headline':item.get('title',''),'description':item.get('desc',''),'datePublished':item.get('pubDate'),'image':[item.get('thumb','')],'articleSection':item.get('storyCategory',item.get('category','नेपाल')),'author':{'@type':'Organization','name':item.get('source','समाचार स्रोत')},'publisher':{'@type':'Organization','name':'नेपाल न्यूज हब'},'mainEntityOfPage':{'@type':'WebPage','@id':url}},ensure_ascii=False)}</script><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&family=Noto+Sans+Devanagari:wght@400;600;700;800&display=swap" rel="stylesheet"><style>*{{box-sizing:border-box}}body{{margin:0;font-family:Poppins,'Noto Sans Devanagari',sans-serif;background:linear-gradient(135deg,#f8fafc,#eef2ff,#fff1f2);color:#111827}}main{{max-width:900px;margin:auto;padding:20px 14px 60px}}.back{{display:inline-block;margin:8px 0 18px;color:#e11d48;text-decoration:none;font-weight:800;font-size:12px}}article{{background:rgba(255,255,255,.72);backdrop-filter:blur(28px);border:1px solid rgba(255,255,255,.85);border-radius:28px;padding:clamp(20px,5vw,40px);box-shadow:0 25px 70px #0f172a12}}.meta{{font-size:10px;font-weight:800;color:#e11d48}}h1{{font-size:clamp(28px,6vw,54px);line-height:1.08;letter-spacing:-.04em;margin:12px 0 16px}}.cover{{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:22px;display:block;background:#e2e8f0}}.desc{{font-size:15px;line-height:1.9;color:#475569}}.original{{display:inline-block;background:#111;color:white;padding:12px 18px;border-radius:14px;text-decoration:none;font-size:11px;font-weight:800}}a{{color:#e11d48}}small{{color:#64748b}}@media(max-width:600px){{article{{border-radius:22px;padding:20px}}h1{{font-size:30px}}}}</style></head><body><main><a class="back" href="../">← नेपाल न्यूज हबमा फर्कनुहोस्</a><article><div class="meta">{src} · {cat}</div><h1>{t}</h1><small>{pub}</small><img class="cover" src="{img}" alt="{t}" loading="eager"><p class="desc">{d}</p><a class="original" href="{escape(item.get('link','#'))}" target="_blank" rel="noopener noreferrer">मूल समाचार पढ्नुहोस् ↗</a>{('<h2>सम्बन्धित रिपोर्ट</h2><ul>'+links+'</ul>') if links else ''}</article></main></body></html>'''
paths=[]
for i,item in enumerate(items):
 n=name_for(item,i);paths.append(n);related=[name_for(x,j) for j,x in enumerate(items) if x.get('storyId')==item.get('storyId') and x.get('link')!=item.get('link')][:6];url=f'https://apps.laxmannepal.com.np/Nepal-News-Hub-Pro/news-pages/{n}.html';(OUT/f'{n}.html').write_text(page(item,url,related),encoding='utf-8')
urls=['https://apps.laxmannepal.com.np/Nepal-News-Hub-Pro/']+[f'https://apps.laxmannepal.com.np/Nepal-News-Hub-Pro/news-pages/{n}.html' for n in paths];xml='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{escape(u)}</loc></url>' for u in dict.fromkeys(urls))+'</urlset>'; (ROOT/'sitemap.xml').write_text(xml,encoding='utf-8')
